# Generated by Django 3.1.7 on 2021-04-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_creams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_items_idx',
        ),
    ]
